# Site settings
title: Blog under construction

# URL settings
# Update this to match your folder name!
baseurl: "/blog" 
url: "https://sloth-phd.github.io" 

# Navigation Links (The "Tabs")
header_pages:
  - about.md
  - speech-ai.md
  - music.md
  - games.md
  - comics.md

# Build settings
theme: minima
