# Site settings
title: Sloth PhD Blog
baseurl: "/blog" # Important since your repo is named 'blog'
url: "https://sloth-phd.github.io"

# This section creates your navigation menu
header_pages:
  - about.md
  - food.md
  - gaming.md
  - music.md
  - speech-science.md

theme: minima
plugins:
  - jekyll-feed
